create table public.subjects (
  id_subject bigint generated by default as identity not null,
  name character varying null default '50'::character varying,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp without time zone null default now(),
  constraint subjects_pkey primary key (id_subject),
  constraint subjects_id_subject_key unique (id_subject)
) TABLESPACE pg_default;


alter table public.subjects
alter column id_subject type uuid using gen_random_uuid();